# Generated by Django 4.2.3 on 2023-07-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Todo List', 'verbose_name_plural': 'Todo Lists'},
        ),
    ]
