# Generated by Django 4.2.3 on 2023-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachement',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
